// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACNA--gxhj4kTo1kJTrxZDkaSPgP8UDG8',
    appId: '1:419179795116:web:5958b521ea7bfed7538509',
    messagingSenderId: '419179795116',
    projectId: 'flutter-firebase-e492a',
    authDomain: 'flutter-firebase-e492a.firebaseapp.com',
    storageBucket: 'flutter-firebase-e492a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmf7K7b76kTCaYkJs1JFIwnhKlIY4wB-k',
    appId: '1:419179795116:android:b1a11f2ca45a8d2e538509',
    messagingSenderId: '419179795116',
    projectId: 'flutter-firebase-e492a',
    storageBucket: 'flutter-firebase-e492a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbxSBaqVBYRDYaJwC-LAmsXRdzlDvRPug',
    appId: '1:419179795116:ios:bc019ebf0079cfd3538509',
    messagingSenderId: '419179795116',
    projectId: 'flutter-firebase-e492a',
    storageBucket: 'flutter-firebase-e492a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbxSBaqVBYRDYaJwC-LAmsXRdzlDvRPug',
    appId: '1:419179795116:ios:bc019ebf0079cfd3538509',
    messagingSenderId: '419179795116',
    projectId: 'flutter-firebase-e492a',
    storageBucket: 'flutter-firebase-e492a.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACNA--gxhj4kTo1kJTrxZDkaSPgP8UDG8',
    appId: '1:419179795116:web:af4492da93c691f1538509',
    messagingSenderId: '419179795116',
    projectId: 'flutter-firebase-e492a',
    authDomain: 'flutter-firebase-e492a.firebaseapp.com',
    storageBucket: 'flutter-firebase-e492a.appspot.com',
  );
}
